version: 1.26

run:
  timeout: 5m
  tests: true
  skip-dirs-use-default: false
  skip-dirs:
    - vendor
    - node_modules

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unused
    - goimports
    - gosimple
    - gocritic
    - bodyclose
    - noctx
    - sqlclosecheck

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
  govet:
    check-shadowing: true
  goimports:
    local-prefixes: github.com/artyomstank/virtual_deanery

issues:
  exclude-rules:
    - text: "G601"
      linters:
        - gosec
