-- migrations/000001_init.down.sql

BEGIN;

DROP VIEW IF EXISTS acl;

DROP TABLE IF EXISTS raspisanie_ekzamenov CASCADE;
DROP TABLE IF EXISTS poseshchaemost CASCADE;
DROP TABLE IF EXISTS vedomost CASCADE;
DROP TABLE IF EXISTS dose CASCADE;
DROP TABLE IF EXISTS student CASCADE;
DROP TABLE IF EXISTS raspisanie CASCADE;
DROP TABLE IF EXISTS zanyatiya CASCADE;
DROP TABLE IF EXISTS discipliny CASCADE;
DROP TABLE IF EXISTS istoriya_trudoustrojstva CASCADE;
DROP TABLE IF EXISTS prepodavateli CASCADE;
DROP TABLE IF EXISTS gruppa CASCADE;
DROP TABLE IF EXISTS napravlenie CASCADE;
DROP TABLE IF EXISTS kafedra CASCADE;
DROP TABLE IF EXISTS kabinety CASCADE;

DROP TABLE IF EXISTS audit_log CASCADE;
DROP TABLE IF EXISTS acl_entries CASCADE;
DROP TABLE IF EXISTS user_roles CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS resources CASCADE;
DROP TABLE IF EXISTS roles CASCADE;

DROP FUNCTION IF EXISTS app_current_role();
DROP FUNCTION IF EXISTS app_current_kafedra_id();
DROP FUNCTION IF EXISTS set_updated_at();

COMMIT;
