-- =============================================================
--  VIRTUAL DEANERY DATABASE SCHEMA
--  PostgreSQL 17
--  Password hashes are produced by the backend (bcrypt, cost >= 12).
-- =============================================================

BEGIN;

CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";
CREATE EXTENSION IF NOT EXISTS "citext";

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION app_current_kafedra_id()
RETURNS INT
LANGUAGE sql
STABLE
AS $$
    SELECT NULLIF(current_setting('app.current_kafedra_id', TRUE), '')::INT;
$$;

CREATE OR REPLACE FUNCTION app_current_role()
RETURNS TEXT
LANGUAGE sql
STABLE
AS $$
    SELECT COALESCE(NULLIF(current_setting('app.current_role', TRUE), ''), 'anonymous');
$$;

-- =============================================================
-- 1. AUTH & ACL
-- =============================================================

CREATE TABLE roles (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50) UNIQUE NOT NULL CHECK (name IN ('admin', 'teacher', 'student', 'dean')),
    description TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE resources (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) UNIQUE NOT NULL,
    description TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE users (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      CITEXT UNIQUE NOT NULL,
    email         CITEXT UNIQUE NOT NULL,
    password_hash TEXT   NOT NULL CHECK (length(password_hash) >= 20),
    status        VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'blocked', 'pending')),
    is_active     BOOLEAN     NOT NULL DEFAULT TRUE,
    last_login_at TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (position('@' IN email::TEXT) > 1)
);

CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- One user has one active system role. Composite PK is kept for backend
-- compatibility, UNIQUE(user_id) enforces the "one user - one role" rule.
CREATE TABLE user_roles (
    user_id     INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_id     INT NOT NULL REFERENCES roles(id) ON DELETE RESTRICT,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, role_id),
    UNIQUE (user_id)
);

-- Kept as acl_entries because the current Go repository queries it directly.
CREATE TABLE acl_entries (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id     INT NOT NULL REFERENCES roles(id)     ON DELETE CASCADE,
    resource_id INT NOT NULL REFERENCES resources(id) ON DELETE CASCADE,
    can_read    BOOLEAN NOT NULL DEFAULT FALSE,
    can_write   BOOLEAN NOT NULL DEFAULT FALSE,
    can_delete  BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (role_id, resource_id)
);

CREATE TRIGGER trg_acl_entries_updated_at
BEFORE UPDATE ON acl_entries
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE VIEW acl AS
SELECT
    a.id,
    a.role_id,
    r.name AS role_name,
    a.resource_id,
    res.name AS resource_name,
    a.can_read,
    a.can_write,
    a.can_delete,
    a.created_at,
    a.updated_at
FROM acl_entries a
JOIN roles r ON r.id = a.role_id
JOIN resources res ON res.id = a.resource_id;

CREATE TABLE audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     INT REFERENCES users(id) ON DELETE SET NULL,
    action      VARCHAR(255) NOT NULL,
    resource    VARCHAR(100),
    resource_id TEXT,
    ip_address  INET,
    user_agent  TEXT,
    metadata    JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================
-- 2. DOMAIN
-- =============================================================

CREATE TABLE kabinety (
    id                   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nazvanie             VARCHAR(255) NOT NULL,
    korpus               VARCHAR(100),
    etazh                INT CHECK (etazh IS NULL OR etazh BETWEEN -2 AND 30),
    nalichie_doski       BOOLEAN NOT NULL DEFAULT FALSE,
    nalichie_proektora   BOOLEAN NOT NULL DEFAULT FALSE,
    nalichie_kompyuterov BOOLEAN NOT NULL DEFAULT FALSE,
    vmestimost           INT CHECK (vmestimost IS NULL OR vmestimost > 0),
    tip_kabineta         VARCHAR(100),
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (nazvanie, korpus)
);

CREATE TRIGGER trg_kabinety_updated_at
BEFORE UPDATE ON kabinety
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE kafedra (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nazvanie        VARCHAR(255) UNIQUE NOT NULL,
    kabinet         VARCHAR(100),
    id_zav_kafedroy INT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_kafedra_updated_at
BEFORE UPDATE ON kafedra
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE napravlenie (
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fakultet         VARCHAR(255),
    nazvanie         VARCHAR(255) NOT NULL,
    id_kafedry       INT NOT NULL REFERENCES kafedra(id) ON DELETE RESTRICT,
    profil           VARCHAR(255),
    stepen           VARCHAR(100) CHECK (stepen IS NULL OR stepen IN ('бакалавриат', 'специалитет', 'магистратура', 'аспирантура')),
    data_prinyatiya  DATE,
    kod_napravleniya VARCHAR(50) UNIQUE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_napravlenie_updated_at
BEFORE UPDATE ON napravlenie
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE gruppa (
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nazvanie         VARCHAR(50) UNIQUE NOT NULL,
    kurs             INT NOT NULL CHECK (kurs BETWEEN 1 AND 6),
    semestr          INT NOT NULL CHECK (semestr BETWEEN 1 AND 12),
    forma_obucheniya VARCHAR(100) NOT NULL CHECK (forma_obucheniya IN ('очная', 'заочная', 'очно-заочная')),
    id_napravleniya  INT REFERENCES napravlenie(id) ON DELETE SET NULL,
    id_kuratora      INT,
    god_nabora       INT CHECK (god_nabora IS NULL OR god_nabora BETWEEN 2000 AND 2100),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_gruppa_updated_at
BEFORE UPDATE ON gruppa
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE prepodavateli (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         INT UNIQUE REFERENCES users(id) ON DELETE SET NULL,
    familiya        VARCHAR(100) NOT NULL,
    imya            VARCHAR(100) NOT NULL,
    otchestvo       VARCHAR(100),
    pol             VARCHAR(20) CHECK (pol IS NULL OR pol IN ('мужской', 'женский')),
    data_rozhdeniya DATE,
    telefon         VARCHAR(30),
    email           CITEXT,
    uchenaya_stepen VARCHAR(100),
    dolzhnost       VARCHAR(100),
    tabelnyy_nomer  VARCHAR(50) UNIQUE,
    id_kafedry      INT REFERENCES kafedra(id) ON DELETE SET NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_prepodavateli_updated_at
BEFORE UPDATE ON prepodavateli
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE kafedra
    ADD CONSTRAINT fk_kafedra_zav_kafedroy
    FOREIGN KEY (id_zav_kafedroy) REFERENCES prepodavateli(id) ON DELETE SET NULL;

ALTER TABLE gruppa
    ADD CONSTRAINT fk_gruppa_kurator
    FOREIGN KEY (id_kuratora) REFERENCES prepodavateli(id) ON DELETE SET NULL;

CREATE TABLE istoriya_trudoustrojstva (
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_prepodavatelya   INT NOT NULL REFERENCES prepodavateli(id) ON DELETE CASCADE,
    data_nachala        DATE NOT NULL,
    data_okonchaniya    DATE,
    tip_zanyatosti      VARCHAR(100) CHECK (tip_zanyatosti IS NULL OR tip_zanyatosti IN ('полная', 'частичная', 'совместитель')),
    nazvanie_dolzhnosti VARCHAR(255),
    primechaniya        TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (data_okonchaniya IS NULL OR data_okonchaniya >= data_nachala)
);

CREATE TABLE discipliny (
    id                    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nazvanie              VARCHAR(255) NOT NULL,
    format_attestacii     VARCHAR(100) CHECK (format_attestacii IS NULL OR format_attestacii IN ('экзамен', 'зачёт', 'зачёт с оценкой')),
    id_kafedry            INT REFERENCES kafedra(id)       ON DELETE SET NULL,
    id_prepodavatelya     INT REFERENCES prepodavateli(id) ON DELETE SET NULL,
    kolichestvo_lekcij    INT NOT NULL DEFAULT 0 CHECK (kolichestvo_lekcij >= 0),
    kolichestvo_seminarov INT NOT NULL DEFAULT 0 CHECK (kolichestvo_seminarov >= 0),
    kolichestvo_lab_rabot INT NOT NULL DEFAULT 0 CHECK (kolichestvo_lab_rabot >= 0),
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (nazvanie, id_kafedry)
);

CREATE TRIGGER trg_discipliny_updated_at
BEFORE UPDATE ON discipliny
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE zanyatiya (
    id                          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_gruppy                   INT NOT NULL REFERENCES gruppa(id)     ON DELETE RESTRICT,
    id_discipliny               INT NOT NULL REFERENCES discipliny(id) ON DELETE RESTRICT,
    id_prepodavatelya_lekcij    INT REFERENCES prepodavateli(id)       ON DELETE SET NULL,
    id_prepodavatelya_seminarov INT REFERENCES prepodavateli(id)       ON DELETE SET NULL,
    id_prepodavatelya_lab_rabot INT REFERENCES prepodavateli(id)       ON DELETE SET NULL,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (id_gruppy, id_discipliny)
);

CREATE TABLE raspisanie (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_zanyatiya  INT NOT NULL REFERENCES zanyatiya(id) ON DELETE CASCADE,
    id_kabineta   INT NOT NULL REFERENCES kabinety(id)  ON DELETE RESTRICT,
    tip_zanyatiya VARCHAR(100) CHECK (tip_zanyatiya IS NULL OR tip_zanyatiya IN ('лекция', 'семинар', 'лаб')),
    data_i_vremya TIMESTAMPTZ NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (id_kabineta, data_i_vremya),
    UNIQUE (id_zanyatiya, data_i_vremya)
);

CREATE TABLE student (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         INT UNIQUE REFERENCES users(id) ON DELETE SET NULL,
    familiya        VARCHAR(100) NOT NULL,
    imya            VARCHAR(100) NOT NULL,
    otchestvo       VARCHAR(100),
    pol             VARCHAR(20) CHECK (pol IS NULL OR pol IN ('мужской', 'женский')),
    grazhdanstvo    VARCHAR(100),
    email           CITEXT,
    nomer_telefona  VARCHAR(30),
    data_rozhdeniya DATE,
    inn             VARCHAR(20) UNIQUE,
    snils           VARCHAR(20) UNIQUE,
    pasport         VARCHAR(50) UNIQUE,
    status          VARCHAR(50) NOT NULL DEFAULT 'активный' CHECK (status IN ('активный', 'академотпуск', 'отчислен')),
    oplata          VARCHAR(50) CHECK (oplata IS NULL OR oplata IN ('бюджет', 'контракт')),
    rol             VARCHAR(50) CHECK (rol IS NULL OR rol IN ('студент', 'магистрант', 'аспирант')),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_student_updated_at
BEFORE UPDATE ON student
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE dose (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_studenta     INT NOT NULL REFERENCES student(id)     ON DELETE CASCADE,
    nazvanie        VARCHAR(255),
    id_gruppy       INT REFERENCES gruppa(id)               ON DELETE SET NULL,
    uspevaemost     TEXT,
    id_napravleniya INT REFERENCES napravlenie(id)          ON DELETE SET NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_dose_updated_at
BEFORE UPDATE ON dose
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE vedomost (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_studenta INT NOT NULL REFERENCES student(id)     ON DELETE CASCADE,
    id_predmeta INT NOT NULL REFERENCES discipliny(id)  ON DELETE RESTRICT,
    modul_1     NUMERIC(5,2) CHECK (modul_1 BETWEEN 0 AND 100),
    modul_2     NUMERIC(5,2) CHECK (modul_2 BETWEEN 0 AND 100),
    attestaciya VARCHAR(100),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (id_studenta, id_predmeta)
);

CREATE TRIGGER trg_vedomost_updated_at
BEFORE UPDATE ON vedomost
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE poseshchaemost (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_studenta    INT NOT NULL REFERENCES student(id)    ON DELETE CASCADE,
    id_zanyatiya   INT NOT NULL REFERENCES zanyatiya(id)  ON DELETE CASCADE,
    data_zanyatiya DATE NOT NULL,
    prisutstvoval  BOOLEAN NOT NULL DEFAULT FALSE,
    primechaniya   TEXT,
    UNIQUE (id_studenta, id_zanyatiya, data_zanyatiya)
);

CREATE TABLE raspisanie_ekzamenov (
    id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_gruppy         INT NOT NULL REFERENCES gruppa(id)        ON DELETE CASCADE,
    id_discipliny     INT NOT NULL REFERENCES discipliny(id)    ON DELETE RESTRICT,
    id_prepodavatelya INT REFERENCES prepodavateli(id)          ON DELETE SET NULL,
    id_kabineta       INT NOT NULL REFERENCES kabinety(id)      ON DELETE RESTRICT,
    data_ekzamena     DATE NOT NULL,
    vremya_ekzamena   TIME NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (id_kabineta, data_ekzamena, vremya_ekzamena),
    UNIQUE (id_gruppy, id_discipliny)
);

CREATE TRIGGER trg_raspisanie_ekzamenov_updated_at
BEFORE UPDATE ON raspisanie_ekzamenov
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =============================================================
-- 3. RLS
-- =============================================================

ALTER TABLE vedomost ENABLE ROW LEVEL SECURITY;
ALTER TABLE discipliny ENABLE ROW LEVEL SECURITY;

CREATE POLICY vedomost_admin_all ON vedomost
    FOR ALL
    USING (app_current_role() = 'admin')
    WITH CHECK (app_current_role() = 'admin');

CREATE POLICY discipliny_admin_all ON discipliny
    FOR ALL
    USING (app_current_role() = 'admin')
    WITH CHECK (app_current_role() = 'admin');

CREATE POLICY dean_vedomost ON vedomost
    FOR ALL
    USING (
        app_current_role() = 'dean'
        AND id_predmeta IN (
            SELECT d.id FROM discipliny d
            WHERE d.id_kafedry = app_current_kafedra_id()
        )
    )
    WITH CHECK (
        app_current_role() = 'dean'
        AND id_predmeta IN (
            SELECT d.id FROM discipliny d
            WHERE d.id_kafedry = app_current_kafedra_id()
        )
    );

CREATE POLICY dean_discipliny ON discipliny
    FOR ALL
    USING (app_current_role() = 'dean' AND id_kafedry = app_current_kafedra_id())
    WITH CHECK (app_current_role() = 'dean' AND id_kafedry = app_current_kafedra_id());

-- =============================================================
-- 4. INDEXES
-- =============================================================

CREATE INDEX idx_users_email               ON users(email);
CREATE INDEX idx_users_username            ON users(username);
CREATE INDEX idx_users_status              ON users(status);
CREATE INDEX idx_user_roles_user_id        ON user_roles(user_id);
CREATE INDEX idx_user_roles_role_id        ON user_roles(role_id);
CREATE INDEX idx_acl_entries_role_resource ON acl_entries(role_id, resource_id);
CREATE INDEX idx_acl_entries_resource_id   ON acl_entries(resource_id);
CREATE INDEX idx_audit_log_user_time       ON audit_log(user_id, created_at DESC);
CREATE INDEX idx_audit_log_metadata_gin    ON audit_log USING gin (metadata);

CREATE INDEX idx_prep_fio_trgm ON prepodavateli USING gin ((familiya || ' ' || imya || ' ' || COALESCE(otchestvo, '')) gin_trgm_ops);
CREATE INDEX idx_prep_kafedra  ON prepodavateli(id_kafedry);
CREATE INDEX idx_prep_user     ON prepodavateli(user_id);

CREATE INDEX idx_ist_prepodavatel ON istoriya_trudoustrojstva(id_prepodavatelya);
CREATE INDEX idx_ist_daty         ON istoriya_trudoustrojstva(data_nachala, data_okonchaniya);

CREATE INDEX idx_disc_kafedra       ON discipliny(id_kafedry);
CREATE INDEX idx_disc_prepodavatel  ON discipliny(id_prepodavatelya);
CREATE INDEX idx_disc_nazvanie_trgm ON discipliny USING gin (nazvanie gin_trgm_ops);

CREATE INDEX idx_zan_gruppa   ON zanyatiya(id_gruppy);
CREATE INDEX idx_zan_disc     ON zanyatiya(id_discipliny);
CREATE INDEX idx_zan_prep_lek ON zanyatiya(id_prepodavatelya_lekcij);
CREATE INDEX idx_zan_prep_sem ON zanyatiya(id_prepodavatelya_seminarov);
CREATE INDEX idx_zan_prep_lab ON zanyatiya(id_prepodavatelya_lab_rabot);

CREATE INDEX idx_rasp_datetime   ON raspisanie(data_i_vremya);
CREATE INDEX idx_rasp_zanyatie   ON raspisanie(id_zanyatiya);
CREATE INDEX idx_rasp_kabinet    ON raspisanie(id_kabineta);
CREATE INDEX idx_rasp_group_time ON raspisanie(id_zanyatiya, data_i_vremya);

CREATE INDEX idx_stud_fio_trgm ON student USING gin ((familiya || ' ' || imya || ' ' || COALESCE(otchestvo, '')) gin_trgm_ops);
CREATE INDEX idx_stud_user     ON student(user_id);
CREATE INDEX idx_stud_status   ON student(status);

CREATE INDEX idx_dose_student     ON dose(id_studenta);
CREATE INDEX idx_dose_gruppa      ON dose(id_gruppy);
CREATE INDEX idx_dose_napravlenie ON dose(id_napravleniya);

CREATE INDEX idx_ved_student         ON vedomost(id_studenta);
CREATE INDEX idx_ved_predmet         ON vedomost(id_predmeta);
CREATE INDEX idx_ved_predmet_student ON vedomost(id_predmeta, id_studenta);

CREATE INDEX idx_kafedra_zav     ON kafedra(id_zav_kafedroy);
CREATE INDEX idx_napr_kafedra    ON napravlenie(id_kafedry);
CREATE INDEX idx_napr_kod        ON napravlenie(kod_napravleniya);
CREATE INDEX idx_gruppa_napr     ON gruppa(id_napravleniya);
CREATE INDEX idx_gruppa_kurator  ON gruppa(id_kuratora);
CREATE INDEX idx_exam_group_date ON raspisanie_ekzamenov(id_gruppy, data_ekzamena);
CREATE INDEX idx_exam_room_time  ON raspisanie_ekzamenov(id_kabineta, data_ekzamena, vremya_ekzamena);
CREATE INDEX idx_att_student_date ON poseshchaemost(id_studenta, data_zanyatiya);

-- =============================================================
-- 5. SEED DATA
-- =============================================================

INSERT INTO roles (name, description) VALUES
    ('admin',   'Системный администратор: пользователи, роли, ACL'),
    ('teacher', 'Преподаватель: занятия, оценки, посещаемость'),
    ('student', 'Студент: просмотр своего профиля, расписания и оценок'),
    ('dean',    'Деканат: управление учебным процессом факультета')
ON CONFLICT (name) DO UPDATE SET description = EXCLUDED.description;

INSERT INTO resources (name, description) VALUES
    ('users',         'Учётные записи пользователей'),
    ('roles',         'Роли и права доступа'),
    ('students',      'Данные студентов'),
    ('grades',        'Ведомости и оценки'),
    ('attendance',    'Посещаемость'),
    ('schedule',      'Расписание занятий'),
    ('exam_schedule', 'Расписание экзаменов'),
    ('teachers',      'Данные преподавателей'),
    ('disciplines',   'Дисциплины и учебные планы'),
    ('departments',   'Кафедры и направления'),
    ('debts',         'Академические задолженности'),
    ('reports',       'Отчётность'),
    ('profile',       'Профиль пользователя')
ON CONFLICT (name) DO UPDATE SET description = EXCLUDED.description;

INSERT INTO acl_entries (role_id, resource_id, can_read, can_write, can_delete)
SELECT r.id, res.id, perms.can_read, perms.can_write, perms.can_delete
FROM (VALUES
    ('admin',   'users',         TRUE, TRUE, TRUE),
    ('admin',   'roles',         TRUE, TRUE, TRUE),
    ('admin',   'students',      TRUE, TRUE, TRUE),
    ('admin',   'grades',        TRUE, TRUE, TRUE),
    ('admin',   'attendance',    TRUE, TRUE, TRUE),
    ('admin',   'schedule',      TRUE, TRUE, TRUE),
    ('admin',   'exam_schedule', TRUE, TRUE, TRUE),
    ('admin',   'teachers',      TRUE, TRUE, TRUE),
    ('admin',   'disciplines',   TRUE, TRUE, TRUE),
    ('admin',   'departments',   TRUE, TRUE, TRUE),
    ('admin',   'debts',         TRUE, TRUE, TRUE),
    ('admin',   'reports',       TRUE, TRUE, TRUE),
    ('admin',   'profile',       TRUE, TRUE, FALSE),

    ('teacher', 'students',      TRUE, FALSE, FALSE),
    ('teacher', 'grades',        TRUE, TRUE,  FALSE),
    ('teacher', 'attendance',    TRUE, TRUE,  FALSE),
    ('teacher', 'schedule',      TRUE, FALSE, FALSE),
    ('teacher', 'exam_schedule', TRUE, FALSE, FALSE),
    ('teacher', 'disciplines',   TRUE, FALSE, FALSE),
    ('teacher', 'profile',       TRUE, TRUE,  FALSE),

    ('student', 'grades',        TRUE, FALSE, FALSE),
    ('student', 'attendance',    TRUE, FALSE, FALSE),
    ('student', 'schedule',      TRUE, FALSE, FALSE),
    ('student', 'exam_schedule', TRUE, FALSE, FALSE),
    ('student', 'profile',       TRUE, TRUE,  FALSE),

    ('dean',    'students',      TRUE, TRUE,  FALSE),
    ('dean',    'grades',        TRUE, TRUE,  FALSE),
    ('dean',    'attendance',    TRUE, TRUE,  FALSE),
    ('dean',    'schedule',      TRUE, TRUE,  TRUE),
    ('dean',    'exam_schedule', TRUE, TRUE,  TRUE),
    ('dean',    'teachers',      TRUE, TRUE,  FALSE),
    ('dean',    'disciplines',   TRUE, TRUE,  FALSE),
    ('dean',    'departments',   TRUE, TRUE,  FALSE),
    ('dean',    'debts',         TRUE, TRUE,  FALSE),
    ('dean',    'reports',       TRUE, FALSE, FALSE),
    ('dean',    'profile',       TRUE, TRUE,  FALSE)
) AS perms(role_name, resource_name, can_read, can_write, can_delete)
JOIN roles r ON r.name = perms.role_name
JOIN resources res ON res.name = perms.resource_name
ON CONFLICT (role_id, resource_id) DO UPDATE
SET can_read = EXCLUDED.can_read,
    can_write = EXCLUDED.can_write,
    can_delete = EXCLUDED.can_delete,
    updated_at = NOW();

-- Seed admin user (password: admin123, bcrypt cost 12)
INSERT INTO users (username, email, password_hash, status, is_active)
VALUES ('admin', 'admin@dekanat.local', '$2a$12$kqEPuG/Uf9w598F9RFuQdOUpmixMQf.dY7.J/rlXfaN7BfO4nRa.e', 'active', true)
ON CONFLICT DO NOTHING;

INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id FROM users u, roles r
WHERE u.email = 'admin@dekanat.local' AND r.name = 'admin'
ON CONFLICT DO NOTHING;

COMMIT;
